spring.application.name=users-service

server.port=8083

spring.datasource.url=${USERS_DATASOURCE_URL:jdbc:postgresql://localhost:5435/users_db}
spring.datasource.username=${USERS_DATASOURCE_USERNAME:users_user}
spring.datasource.password=${USERS_DATASOURCE_PASSWORD:users_pass}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

eureka.client.service-url.defaultZone=${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

management.endpoints.web.exposure.include=health,info

app.jwt.secret=${JWT_SECRET:local-dev-secret-change-me-activity-3-relatos-de-papel-32bytes}
app.jwt.issuer=${JWT_ISSUER:relatos-de-papel-users-service}
app.jwt.ttl-seconds=${JWT_TTL_SECONDS:900}
app.opaque-token.prefix=${OPAQUE_TOKEN_PREFIX:phantom:token:}
