spring.application.name=cloud-gateway

server.port=8080

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

management.endpoints.web.exposure.include=health,info,gateway

spring.cloud.gateway.server.webmvc.routes[0].id=catalogue-service-route
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://catalogue-service
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/catalogue/**
spring.cloud.gateway.server.webmvc.routes[0].filters[0]=StripPrefix=1

spring.cloud.gateway.server.webmvc.routes[1].id=orders-service-route
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://orders-service
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/orders/**
spring.cloud.gateway.server.webmvc.routes[1].filters[0]=StripPrefix=1

spring.cloud.gateway.server.webmvc.routes[2].id=catalogue-acl-search-route
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://catalogue-service
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/catalogue/search
spring.cloud.gateway.server.webmvc.routes[2].predicates[1]=Method=GET
spring.cloud.gateway.server.webmvc.routes[2].filters[0]=RewritePath=/api/catalogue/search,/api/v1/books/search

spring.cloud.gateway.server.webmvc.routes[3].id=orders-acl-create-route
spring.cloud.gateway.server.webmvc.routes[3].uri=lb://orders-service
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/api/orders/create
spring.cloud.gateway.server.webmvc.routes[3].predicates[1]=Method=POST
spring.cloud.gateway.server.webmvc.routes[3].filters[0]=RewritePath=/api/orders/create,/api/v1/orders