spring.application.name=cloud-gateway

server.port=8080

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

management.endpoints.web.exposure.include=health,info,gateway

gateway.security.validation-service-id=users-service
gateway.security.validation-path=/api/v1/auth/validate
gateway.security.access-token-header=accessToken

spring.cloud.gateway.server.webmvc.routes[0].id=users-auth-route
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://users-service
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/v1/auth/**

spring.cloud.gateway.server.webmvc.routes[1].id=users-profile-route
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://users-service
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/v1/users/**

spring.cloud.gateway.server.webmvc.routes[2].id=books-route
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://catalogue-service
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/v1/books/**

spring.cloud.gateway.server.webmvc.routes[3].id=orders-route
spring.cloud.gateway.server.webmvc.routes[3].uri=lb://orders-service
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/api/v1/orders/**

spring.cloud.gateway.server.webmvc.routes[4].id=legacy-catalogue-service-route
spring.cloud.gateway.server.webmvc.routes[4].uri=lb://catalogue-service
spring.cloud.gateway.server.webmvc.routes[4].predicates[0]=Path=/catalogue/**
spring.cloud.gateway.server.webmvc.routes[4].filters[0]=StripPrefix=1

spring.cloud.gateway.server.webmvc.routes[5].id=legacy-orders-service-route
spring.cloud.gateway.server.webmvc.routes[5].uri=lb://orders-service
spring.cloud.gateway.server.webmvc.routes[5].predicates[0]=Path=/orders/**
spring.cloud.gateway.server.webmvc.routes[5].filters[0]=StripPrefix=1

spring.cloud.gateway.server.webmvc.routes[6].id=legacy-catalogue-acl-search-route
spring.cloud.gateway.server.webmvc.routes[6].uri=lb://catalogue-service
spring.cloud.gateway.server.webmvc.routes[6].predicates[0]=Path=/api/catalogue/search
spring.cloud.gateway.server.webmvc.routes[6].predicates[1]=Method=GET
spring.cloud.gateway.server.webmvc.routes[6].filters[0]=RewritePath=/api/catalogue/search,/api/v1/books/search

spring.cloud.gateway.server.webmvc.routes[7].id=legacy-orders-acl-create-route
spring.cloud.gateway.server.webmvc.routes[7].uri=lb://orders-service
spring.cloud.gateway.server.webmvc.routes[7].predicates[0]=Path=/api/orders/create
spring.cloud.gateway.server.webmvc.routes[7].predicates[1]=Method=POST
spring.cloud.gateway.server.webmvc.routes[7].filters[0]=RewritePath=/api/orders/create,/api/v1/orders
